import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI

WebUI.comment("Psalm 201 – En vänlig grönskas rika dräkt")
WebUI.comment("")
WebUI.comment("En vänlig grönskas rika dräkt har smyckat dal och ängar.")
WebUI.comment("Nu smeker vindens ljumma fläkt de fagra örtes-ängar;")
WebUI.comment("Och solens ljus och lundens sus och vågens sorl bland viden")
WebUI.comment("förkunna sommartiden.")
WebUI.comment("")
WebUI.comment("Sin lycka och sin sommar-ro de yra fåglar prisa;")
WebUI.comment("Ur skogens snår, ur stilla bo framklingar deras visa.")
WebUI.comment("En hymn går opp med fröjd och hopp från deras glada kväden")
WebUI.comment("från blommorna och träden")
WebUI.comment("")
WebUI.comment("Men Du, o Gud, som gör vår jord så skön i sommarns stunder,")
WebUI.comment("Giv, att jag aktar främst ditt ord och dina nådesunder,")
WebUI.comment("Allt kött är hö, och blomstren dö och tiden allt fördriver")
WebUI.comment("blott Herrens ord förbliver.")
WebUI.comment("")
WebUI.comment("Musik: Waldemar Åhlén")
WebUI.comment("Text: Carl David af Wirsén")
WebUI.comment("quoted from https://1.se/text-psalm-201-en-vanlig-gronskas-rika-drakt-sommarpsalm/")
