import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.extentreports.ExpandoWebUiBuiltInKeywordsTest

runWithJUnitRunner(ExpandoWebUiBuiltInKeywordsTest.class)
